### PR TITLE
test: (android) use API 29

### PR DESCRIPTION
**Pull request by breautek**
### Platforms affected
Android

### Motivation and Context

Make test use API / Build Tools 29.

Fixes some build errors in travis.

### Description

Updates Travis

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by breautek** [comment]
Blocked by https://github.com/apache/cordova-paramedic/pull/200 and https://github.com/apache/cordova-paramedic/pull/202

**Comment by felipecaparelli** [comment]
> Blocked by [apache/cordova-paramedic#200](https://github.com/apache/cordova-paramedic/pull/200) and [apache/cordova-paramedic#202](https://github.com/apache/cordova-paramedic/pull/202)

Is there any other blocker?

**Comment by breautek** [comment]
> > Blocked by [apache/cordova-paramedic#200](https://github.com/apache/cordova-paramedic/pull/200) and [apache/cordova-paramedic#202](https://github.com/apache/cordova-paramedic/pull/202)
> 
> Is there any other blocker?

We'll see if the tests pass.

**Comment by breautek** [comment]
The failed tests are iOS/browser environments which is unrelated to this PR, so I think it's still okay to merge.

**Review by timbru31 — APPROVED** [review]

**Pull request merged**
