### PR TITLE
CB-7956 Add cordova-plugin-file support for browser platform

### PR DESCRIPTION
**Pull request by vladimir-kotikov**
* Added Firefox and IE support via IndexedDB
* Updated the docs
* Updated the tests

### CODE REVIEW

**Comment by purplecabbage** [comment]
Rebase please

**Comment by vladimir-kotikov** [comment]
@purplecabbage Done.

**Comment by vladimir-kotikov** [comment]
@purplecabbage Ping.

**Comment by vladimir-kotikov** [comment]
Thanks!

**Pull request merged**
