### PR TITLE
fix(android): FileError on a content resolveLocalFileSystemURL

### PR DESCRIPTION
**Pull request by grassick**
### Platforms affected
Android

### Motivation and Context
This solves issue https://github.com/apache/cordova-plugin-file/issues/525 which is a serious problem.

Closes apache/cordova-plugin-file#525

### Description
This implements the fix described in https://github.com/apache/cordova-plugin-file/issues/525#issue-1265882820

### Testing
I tested locally, pushed to production. Approximately 1000 installs working with no issues.

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Review by breautek — APPROVED** [review]

**Comment by erisu** [comment]
Was this tested against both use cases of using either http/https scheme and the file protocol?

**Comment by HarelM** [comment]
Is there any way for me to help push this forward?
I haven't tested this with https, only with "default" capacitor configurations which is http and localhost.

**Comment by realtebo** [comment]
Please, fix this ASAP, because it's blocking some new projects

**Review by erisu — APPROVED** [review]
LGTM

**Pull request merged**
