### PR TITLE
Rework to use normal url form on windows platform

### PR DESCRIPTION
**Pull request by vldmrrr**
CB-7883: toURL method called on etnries returned by resolveLocalFileSystemURL and getDirectory produces path instead of URL. 

This rework produce url's in normal form. The code passes all automated tests, although some tests were massaged for windows platform.

### CODE REVIEW

**Comment by vladimir-kotikov** [comment]
@purplecabbage Could you pls. take a look

**Comment by purplecabbage** [comment]
Initially it looks good.  I am a little weary of some of the differences between all the platforms though, and would like to look at this some more before it is pulled in.

**Comment by vladimir-kotikov** [comment]
@purplecabbage is there any news on this PR?

**Comment by purplecabbage** [comment]
Not yet. On it.

**Comment by purplecabbage** [comment]
Please rebase, + fix the merge conflict, and I will re-evaluate.

Strange this is, when I just update the tests.js file, we only have 1 failing test.

**Comment by vldmrrr** [comment]
rebased

**Pull request merged**
