### PR TITLE
WIP: chore: adds package-lock file

### PR DESCRIPTION
**Pull request by timbru31**
### Motivation and Context

Consistency of our codebases. part of https://github.com/apache/cordova/issues/4. Depends on #405

Closes https://github.com/apache/cordova-plugin-file/pull/442

### CODE REVIEW

**Comment by breautek** [comment]
Why does this depend on #405?

**Comment by timbru31** [comment]
Because the lock file include the dependencies of the `@cordova/eslint-config` package. I'll try to see what's the state of #405 next week 👍

**Comment by breautek** [comment]
> Because the lock file include the dependencies of the `@cordova/eslint-config` package. I'll try to see what's the state of #405 next week

I see. I'll be merging #442 which does not have the same dependency, but I'll update it to not close this PR since it's still valid... or maybe #405 can be rebased to include the `package-lock.json` change.

**Comment by erisu** [comment]
File has already been added.

**Pull request closed without merging**
