### PR TITLE
feat(android): add READ_MEDIA_* permissions for Android 13+

### PR DESCRIPTION
**Pull request by MauriceFrank**
**Refer to :** https://developer.android.com/about/versions/13/behavior-changes-13

image

### CODE REVIEW

**Comment by breautek** [comment]
I enabled test but they will likely fail on Android because it will depend on the platform using Compile SDK 33. The Android should be resolved when cordova-android@12 is released.

**Comment by MauriceFrank** [comment]
> I enabled test but they will likely fail on Android because it will depend on the platform using Compile SDK 33. The Android should be resolved when cordova-android@12 is released.

Actually I just retested and it works fine while just requesting one permission at a time (READ_MEDIA_IMAGES), but it fails reading (file.listDir() with folder "DCIM") when trying to request all at once. Might be a syntax mistake in the PR or another issue. 

Shall I update it or close it? For my own usage, it is enough to request the READ_MEDIA_IMAGES. However, for other users it might not be enough, since it should work with all types of Media. That's why I have tried with this PR to request all needed permissions but obviously it isn't as simple.

As you suggested, the better approach for accessing external storage would be to not use the file-plugin at all anymore and rather use (if existing) a cordova plugin using the MediaStore API.

**Review by erisu — APPROVED** [review]
LGTM

**Comment by ferdianarief** [comment]
So, how about permission to read document like pdf, world and xls from external storage (emulated/0/Download/.....)

i tried copyTo  but still error ( error code : 1)

**Comment by breautek** [comment]
> So, how about permission to read document like pdf, world and xls from external storage (emulated/0/Download/.....)
> 
> i tried copyTo but still error ( error code : 1)

Android has no permission for documents, and by extension doesn't support documents via the file API while working with external storage. Instead you have to use a plugin that interfaces with the native MediaStore API to work with document files. More info on this is noted [here](https://github.com/apache/cordova-plugin-file?tab=readme-ov-file#androids-external-storage-quirks).

**Comment by ferdianarief** [comment]
thanks @breautek  for quick response,

Screen Shot 2024-05-01 at 16 43 31

copying file is unseccessful, and this is my code

window.resolveLocalFileSystemURL(docPath,function (fileEntry)
    {
		console.log(JSON.stringify(fileEntry));
        window.resolveLocalFileSystemURL(cordova.file.dataDirectory,function (directory)
        {              
			console.log(JSON.stringify(directory))    
           fileEntry.moveTo(directory, newFileName,function(){
                alert('Successful Copy!');
            },
            function()
            {
                alert('Copying Unsuccessful ');
            });
        },null);
    }, null);

**Comment by breautek** [comment]
> copying file is unseccessful, and this is my code

Because you're working with a document file, you can't use a filesystem API. You can use filesystem API for internal storage, but not with files on external storage. It looks like you're attempting to move a PDF document from external storage into internal storage. It will error on reading a document from the external storage path (the `/storage/emulated/0/Documents/` path). This is a limitation of Android's Scoped Storage model, which is enforced on API 29 and later.

Generally speaking interacting with files on external storage requires using a media storage API, which this plugin does not implement. See [here](https://www.npmjs.com/search?q=ecosystem%3Acordova%20storage%20access%20framework) for a list of plugins that implements the media store API.

I'm locking this thread because an old merged PR is not really a place to ask questions or to provide support. If you have further questions, please use [Discussions](https://github.com/apache/cordova/discussions) instead.

**Pull request merged**
