### PR TITLE
fix(windows): `readAsBinaryString` only reads the requested range (CB-13208)

### PR DESCRIPTION
**Pull request by salbahra**
### Platforms affected
Windows

### What does this PR do?
Change `readAsBinaryString` on `FileReader` for Windows to use a stream which seeks to the start position and only reads until the requested end instead of reading the entire file to a buffer then slicing the requested fragment.

### What testing has been done on this change?
Plugin change has been tested on Windows as that's the only platform affected.

### Checklist
- [X] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [X] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [X] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by janpio** [comment]
Did I get this right that this basically adds an additional step in between where only the requested part is read into `buffer`?

There seems to be a conflict now, can you fix that by rebasing your changes?

**Comment by salbahra** [comment]
That is correct, I am using the other read methods as a template.

The merge conflicts should be resolved now.

Thanks!

**Comment by salbahra** [comment]
Any status on this PR?

**Comment by janpio** [comment]
Hey, I just fixed the problem that caused Android tests to fail in `master`. Could you rebase this PR please? This should get rid of the Android failures and possibly fix all test failures for this PR.

**Comment by janpio** [comment]
Rerun tests with current config.

**Comment by janpio** [comment]
CI: Once more please.

**Comment by salbahra** [comment]
@janpio Sorry for the delay but just noticed your request. I merged `apache/master` into my fork which has updated this PR. Let me know if there is anything else I can do to help with.

Thanks!

**Comment by janpio** [comment]
Oh sorry, this wasn't even a request - I just have to close, then reopen the PR to trigger a CI rebuild ;) So I was talking to myself or CI (which doesn't listen of course, but rebuilds becaus of the open/close dance I was doing) ;)

**Comment by salbahra** [comment]
Is this PR abandoned or fixed in another PR?

**Comment by salbahra** [comment]
I take this PR will never be merged. Going to close it to remove it from my list of open PRs. This is an issue but I assume the platform has been abandoned.

**Pull request closed without merging**
