### PR TITLE
CB-9891: Fix permission errors due to URI encoding inconsistency on Android

### PR DESCRIPTION
**Pull request by jasongin**

### CODE REVIEW

**Comment by jasongin** [comment]
@riknoll please review

**Comment by jasongin** [comment]
This also fixes CB-7024. CB-9891 is really a duplicate of that one.

**Comment by riknoll** [comment]
LGTM. Tested and ran mobilespec on Marshmallow device.

**Comment by zanemcca** [comment]
@asfgit @stevengill When is the 4.0.0 release expected to be on NPM with this fix?

**Comment by stevengill** [comment]
@zanemcca it is on npm, just not set to latest until we release cordova 6.0.0

cordova plugin add cordova-plugin-file@4.0.0

**Comment by zanemcca** [comment]
@stevengill Thanks

**Pull request merged**
